apiVersion: apps/v1
kind: Deployment
metadata: 
  name: javaapp-deploy
  labels: 
    app: javaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
     containers:
     - name: javaapp-container
       image: 2643/javaapp:2

       ports:
       - containerPort: 8080