apiVersion: v1
kind: ReplicationController
metadata:
  name: login-rc
spec:
  replicas: 4
  selector:
    app: login
  template:
   metadata:
     labels:
      app: login
   spec:
     containers: 
     - name: login-container
       image: maha4iac/myonlinebooking:1
       ports: 
       - containerPort: 80