apiVersion: v1
kind: ReplicationController
metadata:
  name: login-rc
spec:
  replicas: 4
  selector:
    app: login
    version: 2.6.2
  template:
   metadata:
     labels:
      app: login
      version: 2.6.2
   spec:
     containers: 
     - name: login-container
       image: maha4iac/myonlinebooking:2
       ports: 
       - containerPort: 8080