apiVersion: v1
kind: ReplicationController
metadata:
 name: nginx-rc
spec:
 replicas: 4
 selector:
   app: mynginx
 template:
   metadata:
     labels:
       app: mynginx
   spec:
     containers:
     - name: ngnix-container
       image: nginx
       ports:
       - containerPort: 80